events {
}

http {
    upstream backend { 
        server gateway1:9000;
        server gateway2:9000;
        
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}